# Streamlit Dockerfile
FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev

COPY . .

EXPOSE 8501

ENV PYTHONPATH=${PYTHONPATH}:${PWD}

CMD ["streamlit", "run", "Streamlit/main.py", "--server.port=8501", "--server.address=0.0.0.0"]